// src/lib/seed.ts
// Run: npx tsx src/lib/seed.ts
import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/saree-store';

async function seed() {
  await mongoose.connect(MONGODB_URI);
  console.log('Connected to MongoDB');

  // Models inline for seed
  const UserSchema = new mongoose.Schema({ name: String, email: { type: String, unique: true }, password: String, role: String, addresses: [], favourites: [] });
  const ProductSchema = new mongoose.Schema({ name: String, slug: String, description: String, price: Number, discountPrice: Number, category: String, material: String, color: [String], occasion: [String], images: [String], stock: Number, sku: { type: String, unique: true }, tags: [String], featured: Boolean, active: Boolean, ratings: [], averageRating: Number, totalReviews: Number }, { timestamps: true });

  const User = mongoose.models.User || mongoose.model('User', UserSchema);
  const Product = mongoose.models.Product || mongoose.model('Product', ProductSchema);

  // Create admin
  const adminExists = await User.findOne({ email: 'admin@silkdrapes.com' });
  if (!adminExists) {
    const hashed = await bcrypt.hash('admin123', 12);
    await User.create({ name: 'Admin', email: 'admin@silkdrapes.com', password: hashed, role: 'admin', addresses: [], favourites: [] });
    console.log('✅ Admin created: admin@silkdrapes.com / admin123');
  }

  // Sample products
  const products = [
    // ── Kanjivaram ──────────────────────────────────────────────────────────
    {
      name: 'Royal Kanjivaram Silk in Crimson Gold',
      slug: 'royal-kanjivaram-silk-crimson-gold',
      description: 'Exquisite handwoven Kanjivaram silk saree featuring traditional temple border motifs and rich gold zari work. This masterpiece from Tamil Nadu artisans is perfect for weddings and grand celebrations.',
      price: 18500, discountPrice: 15999,
      category: 'Kanjivaram Sarees', material: 'Pure Kanjivaram Silk',
      color: ['Crimson', 'Gold'], occasion: ['Wedding', 'Festival'],
      images: ['https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600'],
      stock: 5, sku: 'KAN-001', tags: ['silk', 'kanjivaram', 'wedding'],
      featured: true, active: true, averageRating: 4.8, totalReviews: 24,
    },
    {
      name: 'Kanjivaram Peacock Green with Gold Zari',
      slug: 'kanjivaram-peacock-green-gold-zari',
      description: 'Traditional Kanjivaram silk in stunning peacock green, adorned with intricate gold zari peacock motifs along the border. A treasured handloom from skilled Tamil Nadu weavers.',
      price: 21000, discountPrice: 17999,
      category: 'Kanjivaram Sarees', material: 'Pure Kanjivaram Silk',
      color: ['Peacock Green', 'Gold'], occasion: ['Wedding', 'Festival', 'Reception'],
      images: ['https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600'],
      stock: 4, sku: 'KAN-002', tags: ['silk', 'kanjivaram', 'peacock', 'zari'],
      featured: true, active: true, averageRating: 4.9, totalReviews: 16,
    },
    {
      name: 'Kanjivaram Dual Tone Pink & Purple',
      slug: 'kanjivaram-dual-tone-pink-purple',
      description: 'A stunning dual-tone Kanjivaram silk saree with a vibrant contrast of rose pink and deep purple. Features a wide zari border with lotus motifs — ideal for sangeet and reception ceremonies.',
      price: 16000, discountPrice: 13500,
      category: 'Kanjivaram Sarees', material: 'Pure Kanjivaram Silk',
      color: ['Pink', 'Purple'], occasion: ['Sangeet', 'Reception', 'Festival'],
      images: ['https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=600'],
      stock: 6, sku: 'KAN-003', tags: ['kanjivaram', 'dual-tone', 'pink', 'purple'],
      featured: false, active: true, averageRating: 4.6, totalReviews: 11,
    },

    // ── Banarasi ─────────────────────────────────────────────────────────────
    {
      name: 'Banarasi Brocade in Peacock Blue',
      slug: 'banarasi-brocade-peacock-blue',
      description: 'Stunning Banarasi brocade saree with intricate peacock motifs woven in golden zari. A timeless piece from the looms of Varanasi, ideal for festive occasions.',
      price: 12000, discountPrice: 9999,
      category: 'Banarasi Sarees', material: 'Banarasi Silk',
      color: ['Peacock Blue', 'Gold'], occasion: ['Wedding', 'Party'],
      images: ['https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600'],
      stock: 8, sku: 'BAN-001', tags: ['banarasi', 'brocade', 'zari'],
      featured: true, active: true, averageRating: 4.7, totalReviews: 18,
    },
    {
      name: 'Banarasi Pure Silk in Sunset Orange',
      slug: 'banarasi-pure-silk-sunset-orange',
      description: 'Vibrant sunset orange Banarasi pure silk saree with fine meenakari work and a rich silver zari border. A radiant choice for Diwali, Navratri and cultural celebrations.',
      price: 14500, discountPrice: 11999,
      category: 'Banarasi Sarees', material: 'Banarasi Silk',
      color: ['Orange', 'Silver'], occasion: ['Festival', 'Party', 'Navratri'],
      images: ['https://images.unsplash.com/photo-1564584217132-2271feaeb3c5?w=600'],
      stock: 7, sku: 'BAN-002', tags: ['banarasi', 'silk', 'festival', 'meenakari'],
      featured: true, active: true, averageRating: 4.5, totalReviews: 20,
    },
    {
      name: 'Banarasi Tissue Silk in Ivory Gold',
      slug: 'banarasi-tissue-silk-ivory-gold',
      description: 'Lightweight Banarasi tissue silk saree with shimmering gold all-over buti work. Elegant and airy, this is perfect for summer weddings and receptions.',
      price: 9500, discountPrice: 7999,
      category: 'Banarasi Sarees', material: 'Banarasi Tissue Silk',
      color: ['Ivory', 'Gold'], occasion: ['Wedding', 'Reception'],
      images: ['https://images.unsplash.com/photo-1594938298603-c8148c4a8bd8?w=600'],
      stock: 10, sku: 'BAN-003', tags: ['banarasi', 'tissue', 'ivory', 'buti'],
      featured: false, active: true, averageRating: 4.4, totalReviews: 9,
    },

    // ── Cotton ───────────────────────────────────────────────────────────────
    {
      name: 'Pure Cotton Jamdani in Ivory White',
      slug: 'pure-cotton-jamdani-ivory',
      description: 'Lightweight pure cotton Jamdani saree with delicate floral motifs. Perfect for daily wear and summer occasions. Breathable and elegant.',
      price: 3500, discountPrice: 2999,
      category: 'Cotton Sarees', material: 'Pure Cotton',
      color: ['Ivory', 'White'], occasion: ['Casual', 'Office', 'Daily'],
      images: ['https://images.unsplash.com/photo-1594938298603-c8148c4a8bd8?w=600'],
      stock: 15, sku: 'COT-001', tags: ['cotton', 'jamdani', 'casual'],
      featured: true, active: true, averageRating: 4.5, totalReviews: 31,
    },
    {
      name: 'Handloom Cotton in Teal & White Stripes',
      slug: 'handloom-cotton-teal-white-stripes',
      description: 'Classic handloom cotton saree in soothing teal and white stripes with a contrast mustard yellow border. Comfortable for long work days and casual outings.',
      price: 2800, discountPrice: 2299,
      category: 'Cotton Sarees', material: 'Handloom Cotton',
      color: ['Teal', 'White', 'Mustard'], occasion: ['Office', 'Casual', 'Daily'],
      images: ['https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?w=600'],
      stock: 18, sku: 'COT-002', tags: ['cotton', 'handloom', 'stripes', 'casual'],
      featured: false, active: true, averageRating: 4.3, totalReviews: 25,
    },
    {
      name: 'Bengal Cotton Tant in Blue & Red',
      slug: 'bengal-cotton-tant-blue-red',
      description: 'Traditional Bengal Tant saree in vibrant blue with red border. Known for its fine weave, lightweight feel and natural breathability. A symbol of Bengali cultural elegance.',
      price: 2200, discountPrice: 1799,
      category: 'Cotton Sarees', material: 'Bengal Tant Cotton',
      color: ['Blue', 'Red'], occasion: ['Puja', 'Casual', 'Cultural'],
      images: ['https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600'],
      stock: 22, sku: 'COT-003', tags: ['tant', 'bengal', 'cotton', 'puja'],
      featured: false, active: true, averageRating: 4.4, totalReviews: 19,
    },

    // ── Bridal ───────────────────────────────────────────────────────────────
    {
      name: 'Bridal Patola Silk in Deep Red',
      slug: 'bridal-patola-silk-deep-red',
      description: 'The legendary double ikat Patola saree from Gujarat, handwoven with a complex resist dyeing technique. A bridal masterpiece that is as much an heirloom as it is a garment.',
      price: 45000, discountPrice: 42000,
      category: 'Bridal Sarees', material: 'Patola Silk',
      color: ['Deep Red', 'Maroon'], occasion: ['Wedding', 'Bridal'],
      images: ['https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=600'],
      stock: 3, sku: 'BRI-001', tags: ['patola', 'bridal', 'silk'],
      featured: true, active: true, averageRating: 5.0, totalReviews: 7,
    },
    {
      name: 'Grand Bridal Kanjivaram in Maroon & Gold',
      slug: 'grand-bridal-kanjivaram-maroon-gold',
      description: 'A magnificent bridal Kanjivaram silk saree in deep maroon with an elaborate gold zari border featuring the iconic temple motifs. Comes with matching blouse piece.',
      price: 55000, discountPrice: 49999,
      category: 'Bridal Sarees', material: 'Pure Kanjivaram Silk',
      color: ['Maroon', 'Gold'], occasion: ['Wedding', 'Bridal'],
      images: ['https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600'],
      stock: 2, sku: 'BRI-002', tags: ['kanjivaram', 'bridal', 'silk', 'zari', 'maroon'],
      featured: true, active: true, averageRating: 5.0, totalReviews: 5,
    },
    {
      name: 'Bridal Benarasi in Ruby Red & Silver',
      slug: 'bridal-banarasi-ruby-red-silver',
      description: 'Opulent bridal Banarasi saree in ruby red with fine silver zari work throughout. The pallu features elaborate peacock and floral motifs — a dream for every bride.',
      price: 38000, discountPrice: 34999,
      category: 'Bridal Sarees', material: 'Banarasi Silk',
      color: ['Ruby Red', 'Silver'], occasion: ['Wedding', 'Bridal'],
      images: ['https://images.unsplash.com/photo-1564584217132-2271feaeb3c5?w=600'],
      stock: 4, sku: 'BRI-003', tags: ['banarasi', 'bridal', 'ruby', 'silver'],
      featured: false, active: true, averageRating: 4.9, totalReviews: 8,
    },

    // ── Designer ─────────────────────────────────────────────────────────────
    {
      name: 'Georgette Designer Saree in Rose Pink',
      slug: 'georgette-designer-rose-pink',
      description: 'Modern designer georgette saree with digital print floral patterns and embellished border. A perfect blend of contemporary style and traditional elegance.',
      price: 5999, discountPrice: 4999,
      category: 'Designer Sarees', material: 'Georgette',
      color: ['Rose Pink', 'Blush'], occasion: ['Party', 'Reception', 'Festival'],
      images: ['https://images.unsplash.com/photo-1564584217132-2271feaeb3c5?w=600'],
      stock: 12, sku: 'DES-001', tags: ['georgette', 'designer', 'party'],
      featured: false, active: true, averageRating: 4.3, totalReviews: 15,
    },
    {
      name: 'Sequin Embroidered Net Saree in Midnight Blue',
      slug: 'sequin-net-saree-midnight-blue',
      description: 'Glamorous midnight blue net saree with all-over silver sequin embroidery and a heavily embellished pallu. Perfect for cocktail parties, receptions and New Year celebrations.',
      price: 8500, discountPrice: 6999,
      category: 'Designer Sarees', material: 'Net',
      color: ['Midnight Blue', 'Silver'], occasion: ['Party', 'Reception', 'Cocktail'],
      images: ['https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600'],
      stock: 9, sku: 'DES-002', tags: ['net', 'sequin', 'party', 'embroidered'],
      featured: true, active: true, averageRating: 4.6, totalReviews: 13,
    },
    {
      name: 'Chiffon Printed Saree in Coral Bliss',
      slug: 'chiffon-printed-saree-coral-bliss',
      description: 'Soft chiffon saree with vibrant coral and aqua digital floral print. Lightweight and flowy, it drapes beautifully for parties and festive evenings.',
      price: 4200, discountPrice: 3499,
      category: 'Designer Sarees', material: 'Chiffon',
      color: ['Coral', 'Aqua'], occasion: ['Party', 'Festival', 'Casual'],
      images: ['https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?w=600'],
      stock: 14, sku: 'DES-003', tags: ['chiffon', 'printed', 'coral', 'floral'],
      featured: true, active: true, averageRating: 4.2, totalReviews: 28,
    },

    // ── Linen / Casual ───────────────────────────────────────────────────────
    {
      name: 'Linen Handloom in Earthy Tones',
      slug: 'linen-handloom-earthy',
      description: 'Eco-friendly handloom linen saree with natural dyes in earthy tones. Sustainable fashion meets timeless elegance. Ideal for office wear and casual outings.',
      price: 4500,
      category: 'Casual Wear', material: 'Linen',
      color: ['Beige', 'Terracotta', 'Olive'], occasion: ['Office', 'Casual'],
      images: ['https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?w=600'],
      stock: 20, sku: 'LIN-001', tags: ['linen', 'handloom', 'sustainable'],
      featured: false, active: true, averageRating: 4.4, totalReviews: 22,
    },
    {
      name: 'Organic Linen in Forest Green',
      slug: 'organic-linen-forest-green',
      description: 'Naturally dyed organic linen saree in deep forest green. Zero-chemical process, soft texture and breathable weave make this ideal for eco-conscious fashionistas.',
      price: 3800, discountPrice: 3199,
      category: 'Casual Wear', material: 'Organic Linen',
      color: ['Forest Green', 'Off-White'], occasion: ['Office', 'Casual', 'Daily'],
      images: ['https://images.unsplash.com/photo-1594938298603-c8148c4a8bd8?w=600'],
      stock: 16, sku: 'LIN-002', tags: ['linen', 'organic', 'eco', 'green'],
      featured: false, active: true, averageRating: 4.5, totalReviews: 17,
    },

    // ── Silk Sarees ──────────────────────────────────────────────────────────
    {
      name: 'Mysore Silk in Royal Purple',
      slug: 'mysore-silk-royal-purple',
      description: 'Authentic Mysore silk saree in regal deep purple with contrasting gold border. Known for its exceptional sheen and smooth texture, Mysore silk is among India\'s finest.',
      price: 11000, discountPrice: 8999,
      category: 'Silk Sarees', material: 'Mysore Silk',
      color: ['Purple', 'Gold'], occasion: ['Festival', 'Party', 'Pooja'],
      images: ['https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600'],
      stock: 8, sku: 'SLK-001', tags: ['mysore', 'silk', 'purple', 'festival'],
      featured: true, active: true, averageRating: 4.7, totalReviews: 21,
    },
    {
      name: 'Tussar Silk in Mustard Yellow',
      slug: 'tussar-silk-mustard-yellow',
      description: 'Natural wild silk (Tussar) saree in warm mustard yellow with hand-painted kalamkari motifs. Lightweight, textured and perfect for cultural events and art exhibitions.',
      price: 6800, discountPrice: 5499,
      category: 'Silk Sarees', material: 'Tussar Silk',
      color: ['Mustard', 'Brown'], occasion: ['Cultural', 'Casual', 'Festival'],
      images: ['https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=600'],
      stock: 11, sku: 'SLK-002', tags: ['tussar', 'silk', 'kalamkari', 'mustard'],
      featured: false, active: true, averageRating: 4.4, totalReviews: 14,
    },
    {
      name: 'Chanderi Silk Cotton in Pastel Blue',
      slug: 'chanderi-silk-cotton-pastel-blue',
      description: 'Delicate Chanderi saree with a silk-cotton blend in soft pastel blue. Woven with fine golden thread motifs (bootis) throughout, this is a classic for summer weddings.',
      price: 5200, discountPrice: 4299,
      category: 'Silk Sarees', material: 'Chanderi Silk Cotton',
      color: ['Pastel Blue', 'Gold'], occasion: ['Wedding', 'Festival', 'Reception'],
      images: ['https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600'],
      stock: 13, sku: 'SLK-003', tags: ['chanderi', 'silk-cotton', 'pastel', 'booti'],
      featured: true, active: true, averageRating: 4.6, totalReviews: 19,
    },

    // ── Regional / Special ───────────────────────────────────────────────────
    {
      name: 'Kerala Kasavu Saree in Off-White & Gold',
      slug: 'kerala-kasavu-off-white-gold',
      description: 'The iconic Kerala traditional saree in pristine off-white cotton with broad kasavu (gold) border. A symbol of purity and grace, perfect for Onam, Vishu and temple functions.',
      price: 4000, discountPrice: 3299,
      category: 'Cotton Sarees', material: 'Kerala Cotton',
      color: ['Off-White', 'Gold'], occasion: ['Onam', 'Vishu', 'Festival', 'Temple'],
      images: ['https://images.unsplash.com/photo-1594938298603-c8148c4a8bd8?w=600'],
      stock: 17, sku: 'KER-001', tags: ['kerala', 'kasavu', 'onam', 'traditional'],
      featured: true, active: true, averageRating: 4.8, totalReviews: 35,
    },
    {
      name: 'Pochampally Ikat in Geometric Indigo',
      slug: 'pochampally-ikat-geometric-indigo',
      description: 'Vibrant double-ikat Pochampally saree from Telangana featuring bold geometric patterns in indigo, teal and white. A GI-tagged textile celebrated for its mathematical precision.',
      price: 7500, discountPrice: 6299,
      category: 'Silk Sarees', material: 'Pochampally Silk',
      color: ['Indigo', 'Teal', 'White'], occasion: ['Festival', 'Cultural', 'Casual'],
      images: ['https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?w=600'],
      stock: 9, sku: 'POC-001', tags: ['pochampally', 'ikat', 'geometric', 'telangana'],
      featured: true, active: true, averageRating: 4.7, totalReviews: 23,
    },
    {
      name: 'Sambalpuri Bandha Silk in Crimson',
      slug: 'sambalpuri-bandha-silk-crimson',
      description: 'Authentic Sambalpuri bandha (ikat) silk saree from Odisha in deep crimson with traditional shankha and chakra motifs. A proud heritage of Odishan handloom artistry.',
      price: 8200, discountPrice: 6999,
      category: 'Silk Sarees', material: 'Sambalpuri Silk',
      color: ['Crimson', 'White', 'Black'], occasion: ['Festival', 'Cultural', 'Wedding'],
      images: ['https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600'],
      stock: 7, sku: 'SAM-001', tags: ['sambalpuri', 'ikat', 'odisha', 'bandha'],
      featured: false, active: true, averageRating: 4.6, totalReviews: 12,
    },
    {
      name: 'Bandhani Silk in Rani Pink',
      slug: 'bandhani-silk-rani-pink',
      description: 'Striking Rajasthani Bandhani (tie-dye) silk saree in vibrant rani pink with hundreds of tiny resist-dyed dots creating a stunning pattern. A Rajasthan specialty for festive joy.',
      price: 5500, discountPrice: 4499,
      category: 'Silk Sarees', material: 'Bandhani Silk',
      color: ['Rani Pink', 'Yellow'], occasion: ['Festival', 'Garba', 'Navratri'],
      images: ['https://images.unsplash.com/photo-1564584217132-2271feaeb3c5?w=600'],
      stock: 14, sku: 'BAN-001-BND', tags: ['bandhani', 'rajasthan', 'tie-dye', 'garba'],
      featured: true, active: true, averageRating: 4.5, totalReviews: 27,
    },
    {
      name: 'Organza Silk in Champagne Rose',
      slug: 'organza-silk-champagne-rose',
      description: 'Sheer and gossamer organza silk saree in champagne rose with delicate hand-embroidered floral border. Ethereal and lightweight — perfect for evening parties and cocktail events.',
      price: 6500, discountPrice: 5299,
      category: 'Designer Sarees', material: 'Organza Silk',
      color: ['Champagne', 'Rose Gold'], occasion: ['Party', 'Reception', 'Cocktail'],
      images: ['https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600'],
      stock: 10, sku: 'ORG-001', tags: ['organza', 'silk', 'sheer', 'embroidered'],
      featured: true, active: true, averageRating: 4.6, totalReviews: 18,
    },

    // ── Kanjivaram (continued) ──────────────────────────────────────────────
    {
      name: 'Kanjivaram Bridal in Emerald Green & Ruby',
      slug: 'kanjivaram-bridal-emerald-ruby',
      description: 'Stunning emerald green Kanjivaram bridal silk with bold ruby red contrast border and rich gold zari buttas throughout the body. A regal choice for South Indian brides.',
      price: 32000, discountPrice: 27999,
      category: 'Kanjivaram Sarees', material: 'Pure Kanjivaram Silk',
      color: ['Emerald Green', 'Ruby Red', 'Gold'], occasion: ['Wedding', 'Bridal', 'Reception'],
      images: ['https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600'],
      stock: 3, sku: 'KAN-004', tags: ['kanjivaram', 'bridal', 'emerald', 'ruby'],
      featured: true, active: true, averageRating: 4.9, totalReviews: 8,
    },
    {
      name: 'Kanjivaram Half & Half in Blue & Pink',
      slug: 'kanjivaram-half-half-blue-pink',
      description: 'Modern half & half Kanjivaram silk combining serene blue and blush pink with a contrasting gold zari border. A contemporary twist on a timeless classic — perfect for receptions.',
      price: 22000, discountPrice: 18999,
      category: 'Kanjivaram Sarees', material: 'Pure Kanjivaram Silk',
      color: ['Blue', 'Pink', 'Gold'], occasion: ['Reception', 'Wedding', 'Sangeet'],
      images: ['https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600'],
      stock: 5, sku: 'KAN-005', tags: ['kanjivaram', 'half-half', 'blue', 'pink'],
      featured: false, active: true, averageRating: 4.7, totalReviews: 13,
    },
    {
      name: 'Kanjivaram Korvai Silk in Mango Yellow',
      slug: 'kanjivaram-korvai-mango-yellow',
      description: 'Traditional korvai technique Kanjivaram with separate body and border woven together in vivid mango yellow. The intricate weft interlocking makes the border inseparable — a hallmark of authentic craftsmanship.',
      price: 19500, discountPrice: 16999,
      category: 'Kanjivaram Sarees', material: 'Pure Kanjivaram Silk',
      color: ['Mango Yellow', 'Green', 'Gold'], occasion: ['Wedding', 'Festival', 'Seemantham'],
      images: ['https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=600'],
      stock: 4, sku: 'KAN-006', tags: ['kanjivaram', 'korvai', 'mango', 'yellow'],
      featured: false, active: true, averageRating: 4.8, totalReviews: 10,
    },

    // ── Banarasi (continued) ────────────────────────────────────────────────
    {
      name: 'Banarasi Katan Silk in Deep Green',
      slug: 'banarasi-katan-silk-deep-green',
      description: 'Luxurious Banarasi katan silk — the purest form of Banarasi weave — in a rich forest green with all-over silver jangla motifs. A timeless heirloom-quality piece.',
      price: 16000, discountPrice: 13499,
      category: 'Banarasi Sarees', material: 'Banarasi Katan Silk',
      color: ['Forest Green', 'Silver'], occasion: ['Wedding', 'Festival', 'Puja'],
      images: ['https://images.unsplash.com/photo-1564584217132-2271feaeb3c5?w=600'],
      stock: 6, sku: 'BAN-004', tags: ['banarasi', 'katan', 'jangla', 'green'],
      featured: true, active: true, averageRating: 4.8, totalReviews: 15,
    },
    {
      name: 'Banarasi Georgette in Lavender',
      slug: 'banarasi-georgette-lavender',
      description: 'Lightweight Banarasi georgette saree in soft lavender with fine gold zari motifs. The airy fabric drapes effortlessly, making it ideal for summer celebrations and evening parties.',
      price: 7500, discountPrice: 5999,
      category: 'Banarasi Sarees', material: 'Banarasi Georgette',
      color: ['Lavender', 'Gold'], occasion: ['Party', 'Festival', 'Casual'],
      images: ['https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?w=600'],
      stock: 12, sku: 'BAN-005', tags: ['banarasi', 'georgette', 'lavender', 'zari'],
      featured: false, active: true, averageRating: 4.4, totalReviews: 21,
    },
    {
      name: 'Banarasi Shattir Silk in Royal Blue',
      slug: 'banarasi-shattir-silk-royal-blue',
      description: 'Rare Banarasi shattir silk in stunning royal blue with intricate Mughal-inspired floral motifs woven in gold. A collector\'s piece that represents the pinnacle of Varanasi weaving.',
      price: 24000, discountPrice: 20999,
      category: 'Banarasi Sarees', material: 'Banarasi Shattir Silk',
      color: ['Royal Blue', 'Gold'], occasion: ['Wedding', 'Reception', 'Festival'],
      images: ['https://images.unsplash.com/photo-1594938298603-c8148c4a8bd8?w=600'],
      stock: 3, sku: 'BAN-006', tags: ['banarasi', 'shattir', 'mughal', 'royal-blue'],
      featured: true, active: true, averageRating: 4.9, totalReviews: 6,
    },

    // ── Cotton (continued) ──────────────────────────────────────────────────
    {
      name: 'Chettinad Cotton in Black & White Checks',
      slug: 'chettinad-cotton-black-white-checks',
      description: 'Iconic Chettinad cotton saree from Tamil Nadu in classic black and white checks with a colourful thread border. Bold, geometric and effortlessly chic for everyday elegance.',
      price: 2500, discountPrice: 1999,
      category: 'Cotton Sarees', material: 'Chettinad Cotton',
      color: ['Black', 'White'], occasion: ['Office', 'Casual', 'Daily'],
      images: ['https://images.unsplash.com/photo-1594938298603-c8148c4a8bd8?w=600'],
      stock: 25, sku: 'COT-004', tags: ['chettinad', 'cotton', 'checks', 'casual'],
      featured: false, active: true, averageRating: 4.5, totalReviews: 33,
    },
    {
      name: 'Maheshwari Cotton Silk in Peach & Silver',
      slug: 'maheshwari-cotton-silk-peach-silver',
      description: 'Delicate Maheshwari saree from Madhya Pradesh with a silk and cotton blend in soft peach with silver border. Known for its reversible border and fine reversible pallav — ideal for all seasons.',
      price: 4800, discountPrice: 3999,
      category: 'Cotton Sarees', material: 'Maheshwari Silk Cotton',
      color: ['Peach', 'Silver'], occasion: ['Office', 'Festival', 'Casual'],
      images: ['https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600'],
      stock: 15, sku: 'COT-005', tags: ['maheshwari', 'cotton-silk', 'peach', 'madhyapradesh'],
      featured: true, active: true, averageRating: 4.6, totalReviews: 19,
    },
    {
      name: 'Kota Doria Cotton in Mint Green',
      slug: 'kota-doria-cotton-mint-green',
      description: 'Featherlight Kota Doria saree from Rajasthan in refreshing mint green with subtle gold zari checks. The signature square patterns (khat) make this an iconic summer weave.',
      price: 3200, discountPrice: 2599,
      category: 'Cotton Sarees', material: 'Kota Doria Cotton',
      color: ['Mint Green', 'Gold'], occasion: ['Summer', 'Casual', 'Office'],
      images: ['https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?w=600'],
      stock: 20, sku: 'COT-006', tags: ['kota-doria', 'rajasthan', 'mint', 'lightweight'],
      featured: false, active: true, averageRating: 4.3, totalReviews: 28,
    },

    // ── Bridal (continued) ──────────────────────────────────────────────────
    {
      name: 'Bridal Lehenga Saree in Blush Pink',
      slug: 'bridal-lehenga-saree-blush-pink',
      description: 'Trendy lehenga-style saree with a pre-draped blush pink skirt and heavily embellished pallu. Features 3D floral embroidery in gold and pearl work — perfect for modern brides who want a fusion look.',
      price: 28000, discountPrice: 24999,
      category: 'Bridal Sarees', material: 'Net & Satin',
      color: ['Blush Pink', 'Gold', 'Pearl'], occasion: ['Wedding', 'Bridal', 'Reception'],
      images: ['https://images.unsplash.com/photo-1564584217132-2271feaeb3c5?w=600'],
      stock: 5, sku: 'BRI-004', tags: ['lehenga-saree', 'bridal', 'pink', 'embroidered'],
      featured: true, active: true, averageRating: 4.8, totalReviews: 11,
    },
    {
      name: 'Grand Zardozi Bridal in Scarlet Red',
      slug: 'grand-zardozi-bridal-scarlet-red',
      description: 'Magnificent bridal saree in scarlet red velvet with elaborate zardozi (gold thread) hand embroidery throughout. A royal choice for brides who wish to make an unforgettable statement.',
      price: 65000, discountPrice: 58000,
      category: 'Bridal Sarees', material: 'Velvet with Zardozi',
      color: ['Scarlet Red', 'Gold'], occasion: ['Wedding', 'Bridal'],
      images: ['https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=600'],
      stock: 2, sku: 'BRI-005', tags: ['zardozi', 'velvet', 'bridal', 'scarlet', 'royal'],
      featured: true, active: true, averageRating: 5.0, totalReviews: 4,
    },
    {
      name: 'Bridal Georgette in Dusty Rose & Gold',
      slug: 'bridal-georgette-dusty-rose-gold',
      description: 'Elegant bridal georgette saree in dusty rose with intricate gold thread embroidery and sequin work. Lightweight yet glamorous — a contemporary bridal choice for modern ceremonies.',
      price: 18500, discountPrice: 15999,
      category: 'Bridal Sarees', material: 'Embroidered Georgette',
      color: ['Dusty Rose', 'Gold'], occasion: ['Wedding', 'Reception', 'Engagement'],
      images: ['https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600'],
      stock: 6, sku: 'BRI-006', tags: ['georgette', 'bridal', 'dusty-rose', 'sequin'],
      featured: false, active: true, averageRating: 4.7, totalReviews: 14,
    },

    // ── Designer (continued) ────────────────────────────────────────────────
    {
      name: 'Raw Silk Printed in Terracotta Abstract',
      slug: 'raw-silk-printed-terracotta-abstract',
      description: 'Contemporary raw silk saree with bold terracotta and rust abstract digital print. Paired with a sleek contrast blouse, this is a statement piece for art lovers and trendsetters.',
      price: 7200, discountPrice: 5999,
      category: 'Designer Sarees', material: 'Raw Silk',
      color: ['Terracotta', 'Rust', 'Ivory'], occasion: ['Party', 'Cultural', 'Casual'],
      images: ['https://images.unsplash.com/photo-1564584217132-2271feaeb3c5?w=600'],
      stock: 11, sku: 'DES-004', tags: ['raw-silk', 'abstract', 'terracotta', 'printed'],
      featured: false, active: true, averageRating: 4.3, totalReviews: 17,
    },
    {
      name: 'Velvet Border Georgette in Teal',
      slug: 'velvet-border-georgette-teal',
      description: 'Trending georgette saree in vibrant teal with a luxurious velvet and mirror-work border. This fusion of textures creates a visually striking look perfect for festive gatherings.',
      price: 5500, discountPrice: 4499,
      category: 'Designer Sarees', material: 'Georgette with Velvet Border',
      color: ['Teal', 'Gold', 'Mirror'], occasion: ['Party', 'Festival', 'Sangeet'],
      images: ['https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600'],
      stock: 13, sku: 'DES-005', tags: ['georgette', 'velvet', 'teal', 'mirror-work'],
      featured: true, active: true, averageRating: 4.5, totalReviews: 22,
    },
    {
      name: 'Satin Silk Designer in Midnight Black',
      slug: 'satin-silk-designer-midnight-black',
      description: 'Sleek and sophisticated midnight black satin silk saree with gold foil print border and embellished pallu. Effortlessly glamorous — perfect for cocktail evenings and formal galas.',
      price: 9800, discountPrice: 7999,
      category: 'Designer Sarees', material: 'Satin Silk',
      color: ['Black', 'Gold'], occasion: ['Party', 'Cocktail', 'Formal'],
      images: ['https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?w=600'],
      stock: 8, sku: 'DES-006', tags: ['satin', 'black', 'formal', 'gold-foil'],
      featured: true, active: true, averageRating: 4.6, totalReviews: 16,
    },

    // ── Silk Sarees (continued) ─────────────────────────────────────────────
    {
      name: 'Bhagalpuri Silk in Rust & Brown',
      slug: 'bhagalpuri-silk-rust-brown',
      description: 'Authentic Bhagalpuri (Tussar) silk from Bihar in warm rust and brown with block-printed tribal motifs. Textured, natural and earthy — a celebration of India\'s folk art traditions.',
      price: 5800, discountPrice: 4799,
      category: 'Silk Sarees', material: 'Bhagalpuri Silk',
      color: ['Rust', 'Brown', 'Black'], occasion: ['Casual', 'Cultural', 'Festival'],
      images: ['https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600'],
      stock: 14, sku: 'SLK-004', tags: ['bhagalpuri', 'tussar', 'bihar', 'block-print'],
      featured: false, active: true, averageRating: 4.4, totalReviews: 20,
    },
    {
      name: 'Dharmavaram Silk in Bridal Red',
      slug: 'dharmavaram-silk-bridal-red',
      description: 'Grand Dharmavaram silk from Andhra Pradesh in deep bridal red with thick gold zari border and traditional temple motifs on the pallu. A favourite for Telugu weddings and festivals.',
      price: 14500, discountPrice: 12499,
      category: 'Silk Sarees', material: 'Dharmavaram Silk',
      color: ['Bridal Red', 'Gold'], occasion: ['Wedding', 'Festival', 'Puja'],
      images: ['https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=600'],
      stock: 7, sku: 'SLK-005', tags: ['dharmavaram', 'andhra', 'red', 'temple-border'],
      featured: true, active: true, averageRating: 4.7, totalReviews: 18,
    },
    {
      name: 'Pattu Pavadai Set (Girl\'s Silk) in Pink',
      slug: 'pattu-pavadai-girls-silk-pink',
      description: 'Traditional silk pattu pavadai for girls in vibrant pink with gold zari border. Handwoven pure silk for festivals, weddings and naming ceremonies — a cherished gift for little ones.',
      price: 4500, discountPrice: 3799,
      category: 'Silk Sarees', material: 'Pure Silk',
      color: ['Pink', 'Gold'], occasion: ['Festival', 'Wedding', 'Kids'],
      images: ['https://images.unsplash.com/photo-1594938298603-c8148c4a8bd8?w=600'],
      stock: 18, sku: 'SLK-006', tags: ['pattu', 'pavadai', 'kids', 'pink', 'festival'],
      featured: false, active: true, averageRating: 4.8, totalReviews: 30,
    },

    // ── Regional Specials (continued) ───────────────────────────────────────
    {
      name: 'Gadwal Silk in Vermilion & Gold',
      slug: 'gadwal-silk-vermilion-gold',
      description: 'Authentic Gadwal silk from Telangana featuring a cotton body with pure silk border and pallu in rich vermilion and gold. GI-tagged and uniquely comfortable due to the cotton-silk combination.',
      price: 9500, discountPrice: 7999,
      category: 'Silk Sarees', material: 'Gadwal Silk',
      color: ['Vermilion', 'Gold'], occasion: ['Festival', 'Wedding', 'Puja'],
      images: ['https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?w=600'],
      stock: 9, sku: 'GAD-001', tags: ['gadwal', 'telangana', 'vermilion', 'gi-tag'],
      featured: true, active: true, averageRating: 4.7, totalReviews: 14,
    },
    {
      name: 'Manipuri Moirang Phee in Striped Multicolour',
      slug: 'manipuri-moirang-phee-multicolour',
      description: 'Rare handwoven Manipuri Moirang Phee saree with vibrant multicolour stripes and traditional motifs on the border. A unique North-East Indian textile that is both a cultural artefact and a wearable masterpiece.',
      price: 6500, discountPrice: 5299,
      category: 'Cotton Sarees', material: 'Manipuri Cotton Silk',
      color: ['Multicolour', 'Red', 'Yellow', 'Green'], occasion: ['Cultural', 'Festival', 'Casual'],
      images: ['https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600'],
      stock: 8, sku: 'MAN-001', tags: ['manipuri', 'northeast', 'stripes', 'handloom'],
      featured: false, active: true, averageRating: 4.6, totalReviews: 9,
    },
    {
      name: 'Ilkal Saree in Deep Maroon & White',
      slug: 'ilkal-saree-deep-maroon-white',
      description: 'Classic Ilkal saree from Karnataka in deep maroon with contrast white cotton body and traditional tope teni (parrot) motifs on the silk border. A proud Karnataka heritage weave.',
      price: 3800, discountPrice: 3099,
      category: 'Silk Sarees', material: 'Ilkal Silk Cotton',
      color: ['Maroon', 'White'], occasion: ['Festival', 'Puja', 'Cultural'],
      images: ['https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600'],
      stock: 12, sku: 'ILK-001', tags: ['ilkal', 'karnataka', 'maroon', 'tope-teni'],
      featured: false, active: true, averageRating: 4.5, totalReviews: 16,
    },
    {
      name: 'Narayanpet Silk Cotton in Red & Black',
      slug: 'narayanpet-silk-cotton-red-black',
      description: 'Bold Narayanpet saree from Telangana in striking red and black with cotton body and contrasting silk border. The characteristic temple checks and thick border make it instantly recognisable.',
      price: 4200, discountPrice: 3499,
      category: 'Silk Sarees', material: 'Narayanpet Silk Cotton',
      color: ['Red', 'Black'], occasion: ['Festival', 'Puja', 'Casual'],
      images: ['https://images.unsplash.com/photo-1564584217132-2271feaeb3c5?w=600'],
      stock: 11, sku: 'NAR-001', tags: ['narayanpet', 'telangana', 'red', 'checks'],
      featured: false, active: true, averageRating: 4.4, totalReviews: 23,
    },
    {
      name: 'Assam Silk Mekhela Chador in Cream & Red',
      slug: 'assam-silk-mekhela-chador-cream-red',
      description: 'Traditional Assamese Mekhela Chador in natural cream Muga silk with traditional red Assamese motifs (kingkhap). A GI-protected textile that embodies the rich weaving tradition of Assam.',
      price: 11000, discountPrice: 9499,
      category: 'Silk Sarees', material: 'Assam Muga Silk',
      color: ['Cream', 'Red', 'Gold'], occasion: ['Bihu', 'Festival', 'Cultural', 'Wedding'],
      images: ['https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=600'],
      stock: 6, sku: 'ASM-001', tags: ['assam', 'muga', 'mekhela-chador', 'bihu'],
      featured: true, active: true, averageRating: 4.8, totalReviews: 12,
    },
    {
      name: 'Uppada Jamdani Silk in Aqua Blue',
      slug: 'uppada-jamdani-silk-aqua-blue',
      description: 'Delicate Uppada jamdani silk from Andhra Pradesh in refreshing aqua blue with fine white floral jamdani motifs woven across the body. Lightweight and sheer — a beloved summer silk.',
      price: 13500, discountPrice: 11499,
      category: 'Silk Sarees', material: 'Uppada Silk',
      color: ['Aqua Blue', 'White', 'Gold'], occasion: ['Festival', 'Reception', 'Summer'],
      images: ['https://images.unsplash.com/photo-1594938298603-c8148c4a8bd8?w=600'],
      stock: 8, sku: 'UPP-001', tags: ['uppada', 'jamdani', 'andhra', 'aqua'],
      featured: true, active: true, averageRating: 4.7, totalReviews: 15,
    },
    {
      name: 'Venkatagiri Cotton in Soft Yellow & Silver',
      slug: 'venkatagiri-cotton-yellow-silver',
      description: 'Whisper-thin Venkatagiri cotton saree from Andhra Pradesh in soft yellow with fine silver zari border. Prized for its ultra-fine weave and gossamer transparency — a monsoon and summer favourite.',
      price: 4000, discountPrice: 3299,
      category: 'Cotton Sarees', material: 'Venkatagiri Cotton',
      color: ['Yellow', 'Silver'], occasion: ['Summer', 'Office', 'Casual', 'Festival'],
      images: ['https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?w=600'],
      stock: 15, sku: 'VEN-001', tags: ['venkatagiri', 'andhra', 'yellow', 'fine-weave'],
      featured: false, active: true, averageRating: 4.5, totalReviews: 19,
    },
    {
      name: 'Paithani Silk in Parrot Green & Purple',
      slug: 'paithani-silk-parrot-green-purple',
      description: 'Authentic Maharashtrian Paithani silk saree in vivid parrot green body with deep purple pallu, featuring the iconic peacock and lotus motifs woven in pure gold zari. A cultural heirloom from Paithan.',
      price: 29000, discountPrice: 25999,
      category: 'Silk Sarees', material: 'Paithani Silk',
      color: ['Parrot Green', 'Purple', 'Gold'], occasion: ['Wedding', 'Festival', 'Engagement'],
      images: ['https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600'],
      stock: 4, sku: 'PAI-001', tags: ['paithani', 'maharashtra', 'peacock', 'gold-zari'],
      featured: true, active: true, averageRating: 4.9, totalReviews: 10,
    },
  ];

  for (const p of products) {
    const exists = await Product.findOne({ sku: p.sku });
    if (!exists) { await Product.create(p); console.log(`✅ Product: ${p.name}`); }
    else { console.log(`⏭  Skipped (exists): ${p.name}`); }
  }

  console.log('\n🎉 Seed complete!');
  console.log('Admin login: admin@silkdrapes.com / admin123');
  await mongoose.disconnect();
}

seed().catch(console.error);
